#!/bin/bash


# pre-commit.sh
STASH_NAME="pre-commit-$(date +%s)"
git stash save --quiet --keep-index --include-untracked $STASH_NAME

# Test prospective commit
echo "Formatting python code using Black."
black -l 79 $(git ls-tree -r master --name-only | grep ".*\.py")
echo "Running unit tests."
pytest

STASHES=$(git stash list)
if [[ $STASHES == *"$STASH_NAME" ]]; then
  git stash pop --quiet
fi
